#!/usr/bin/env ruby

ENV['BUNDLER_GEMFILE'] = '../Gemfile'
require 'bundler'
require 'pry'

Bundler.setup

ENV["RACK_ENV"] ||= "test"

if ENV['RACK_ENV'] == 'test'
  $stdout.puts "Starting Riak Test Server..."
  require_relative '../test/support/ripple_test_server.rb'
end

$stdout.puts "Loading Enron API Application..."
require_relative 'app/app.rb'
Pry.start

