default: &default
  :enable_encryption: true
  :enable_mapred: true
  :enron_data_path: './enron_mail_20110402/maildir'
  :email_url: 'http://localhost:8098/riak'

development:
  <<: *default
  :enable_encryption: false
  :enable_mapred: true

test:
  <<: *default
  :enable_encryption: true
  :enable_mapred: true


